all: main/server/chat_server.go main/server/client_main.go

gen:
	protoc --proto_path=proto proto/*.proto --go_out=. --go-grpc_out=require_unimplemented_servers=false:.

project:
	go mod init chat-system
	go mod tidy
	go mod verify

server: main/server/chat_server.go
	go build $<

client: main/client/client_main.go
	go build $<

server1: 
	.\chat_server.exe -id 1

clean:
	rm go.mod
	rm go.sum



